#!/usr/bin/env node
import { writeFile, mkdir } from 'node:fs/promises';
import { loadContent } from './parse-content.mjs';

const BANNER =
  '<!-- GENERATED by scripts/build-sheets.mjs — do not edit by hand. Edit content/*.md and re-run `npm run build:sheets`. -->';

const SITE = 'https://sumitgithub1001.github.io/Advancedsa/';
const TIER_NAMES = { 1: 'Foundations', 2: 'Core', 3: 'Advanced', 4: 'Elite' };

const plural = (n) => `${n} problem${n === 1 ? '' : 's'}`;

function line(p, { withPatterns = true } = {}) {
  const bits = [`\`${p.difficulty}\``];
  if (withPatterns && p.patterns?.length) bits.push(p.patterns.join(', '));
  if (p.premium) bits.push('_premium_');
  return `- [ ] [${p.title}](${p.url}) — ${bits.join(' · ')}`;
}

export function renderSheetMarkdown(title, problems) {
  const lines = [
    BANNER,
    '',
    `# ${title}`,
    '',
    `${plural(problems.length)}. Fork this repository and tick the boxes as you go — GitHub renders them live.`,
    '',
  ];

  for (const p of problems) lines.push(line(p));

  lines.push('', '---', '', `Track your progress interactively: **[open the site](${SITE})**`);
  return lines.join('\n') + '\n';
}

export function renderTopicMarkdown(topics, problems) {
  const lines = [
    BANNER,
    '',
    '# The Roadmap',
    '',
    `Every problem, grouped by topic, ordered from beginner to advanced. ${plural(problems.length)}.`,
    '',
    'Each topic opens with what interviewers are actually testing there — the part most sheets leave out.',
    '',
  ];

  let currentTier = null;

  for (const topic of [...topics].sort((a, b) => a.tier - b.tier || a.order - b.order)) {
    const inTopic = problems.filter((p) => p.topic === topic.id);
    if (inTopic.length === 0) continue;

    if (topic.tier !== currentTier) {
      currentTier = topic.tier;
      lines.push(`## Tier ${currentTier} — ${TIER_NAMES[currentTier]}`, '');
    }

    lines.push(`### ${topic.name}`, '', `> ${topic.insight}`, '');
    for (const p of inTopic) lines.push(line(p, { withPatterns: false }));
    lines.push('');
  }

  lines.push('---', '', `Track your progress interactively: **[open the site](${SITE})**`);
  return lines.join('\n') + '\n';
}

async function main() {
  const root = new URL('../', import.meta.url);
  const { topics, problems } = await loadContent(new URL('content/', root));

  await mkdir(new URL('sheets/', root), { recursive: true });

  const sheets = {
    blind75: 'Blind 75',
    'neetcode-150': 'NeetCode 150',
    'striver-sde': 'Striver SDE Sheet',
    'love-babbar': 'Love Babbar Sheet',
  };

  for (const [id, title] of Object.entries(sheets)) {
    const list = problems.filter((p) => p.sheets?.includes(id));
    if (list.length === 0) continue;
    await writeFile(new URL(`sheets/${id}.md`, root), renderSheetMarkdown(title, list));
    console.log(`✓ sheets/${id}.md — ${plural(list.length)}`);
  }

  // No by-topic.md: content/*.md IS the by-topic view, and it is the source.
  // Generating a second copy of it would recreate the drift we designed out.
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
